[package]
name = "rmq-cartesian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ouroboros = "0.18.3"
rand = "0.8.5"
rmq = { git = "https://github.com/daxida/rmq", branch = "main" }
